<?php

return [
    'adminEmail' => 'admin@ecommify.io',
    'senderEmail' => 'noreply@ecommify.io',
    'senderName' => 'ecommify.io',
    'crossOriginAllowedDomains' => ['*'],
    'pageSize' => 10,
    'maropostCurlUrl' => 'https://wolfgroup.neto.com.au/do/WS/NetoAPI', // nato v1 url
    "maropostV2CurlUrl" => "https://api.netodev.com/v1/stores/[api_id]/do/WS/NetoAPI", // nato Legacy V2 url
    'maropostGetAuthTokenCurlUrl' => 'https://api.netodev.com/oauth/v2/token?version=2',
    'woocommerceCurlUrl' => 'https://onesixeightlondon.co.nz/wp-json/wc/v3/',
    'woocommerceShippingCarriersCurlUrl' => 'https://onesixeightlondon.co.nz/wp-json/',
    'amazon_s3' => array(
        'region' => '',
        'Bucket' => '',
        'key' => '',
        'secret' => '',
        'media_url' => '',
    ),
    's3_base_path' => 'ecommify',
    'netoOrderOutputSelectors' => [
        'Username',
        'Email',
        'BillAddress',
        'ShipAddress',
        'DeliveryInstruction',
        'DatePaid',
        'DateInvoiced',
        'DatePlaced',
        'DateCompleted',
        'OrderStatus',
        'PurchaseOrderNumber',
        'OrderLine',
        'OrderLine.Extra',
        'OrderLine.ExtraOptions',
        'OrderLine.PickQuantity',
        'OrderLine.Quantity',
        'OrderLine.ProductName',
        'OrderLine.UnitPrice',
        'OrderLine.ShippingMethod',
        'OrderLine.ShippingTracking',
        'OrderLine.QuantityShipped',
        'ShippingSignature',
        'InternalOrderNotes',
        'OrderLine.ExternalSystemIdentifier',
        'OrderLine.ExternalOrderReference',
        'OrderLine.ExternalOrderLineReference',
        'SalesChannel',
        'OrderPayment',
    ],

    'netoOrderStatus' => [
        'New','New Backorder', 'Backorder Approved',
        'Pick', 'Pack',
        'Pending Pickup', 'Pending Dispatch', 'Dispatched', 
        'Uncommitted', 'On Hold',
    ],
    "maropost_redirect_uri" => "https://app.ecommify.io/integrations/auth/maropost",
    'netoInventoryOutputSelectors' => [
        'ParentSKU', 'UpsellProducts',
        'Name', 'Description', 'ShortDescription', 'AvailableSellQuantity','CommittedQuantity','BaseUnitPerQuantity','QuantityPerScan','BuyUnitQuantity','SellUnitQuantity','PreOrderQuantity', 'virtual', 'ShippingLength', 'ShippingWidth', 
        'ShippingHeight', 'ShippingWeight', 'RelatedContents', 'Categories', 'Approved', 'IsActive', 'PriceGroups', 'RRP', 'DefaultPrice',
        'PromotionPrice', 'PromotionStartDate', 'PromotionExpiryDate', 'Features', 'Brand',
        'Images', 'SEOPageTitle', 'SEOMetaKeywords', 'SEOMetaDescription', 'ItemSpecifics', 'ItemURL',
        'Misc04',
    ],
    'netoProductOutputSelectors' => [
        'ParentSKU', 'UpsellProducts',
        'Name', 'Description', 'ShortDescription', 'AvailableSellQuantity', 'ShippingLength', 'ShippingWidth', 
        'ShippingHeight', 'ShippingWeight', 'RelatedContents', 'Categories', 'Approved', 'IsActive', 'PriceGroups', 'RRP', 'DefaultPrice',
        'PromotionStartDate', 'PromotionExpiryDate', 'Features', 'Brand',
        'Images', 'SEOPageTitle', 'SEOMetaKeywords', 'SEOMetaDescription', 'ItemSpecifics', 'ItemURL',
        'Misc04',
    ],
    'guidLength' => 10
];
